config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :users, except: [:show, :edit]
  resources :categories, only: [:index, :create, :destroy]
  resources :comments, only: [:new, :create]
  resources :votes, only: [:index, :create, :destroy]
  resources :bookmarks, only: [:create, :destroy]
  resources :tags
  resources :articles

  get 'sessions/new'
  get '/signup',  to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'published_articles', to: 'articles#published_articles'
  get 'saved_articles', to: 'articles#saved_articles'
  get 'bookmarks', to: 'articles#bookmarks'
  get 'search', to: 'articles#search'
  get 'create_category', to: 'categories#new'

  get 'profile', to: 'users#show'
  get '/edit_profile', to: 'users#edit'
end

app/models/article.rb
class Article < ApplicationRecord
  before_save :capitalize_title

  belongs_to :author, class_name: 'User'

  belongs_to :category

  has_many :comments, foreign_key: 'article_id', dependent: :destroy

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  has_many :votes, foreign_key: 'article_id', dependent: :destroy
  has_many :voters, through: :votes, source: :user

  has_many :bookmarks, foreign_key: 'article_id', dependent: :destroy
  has_many :bookmarked_readers, through: :bookmarks, source: :user

  mount_uploader :featured_image, FeaturedImageUploader

  validates :title, presence: true, length: { in: 3..50 }
  validates :text, presence: true, length: { minimum: 20 }
  validates :featured_image, :author_id, :category_id, presence: true

  scope :all_published_articles, -> { includes(:category).where('status = ? ', 'published') }

  scope :articles_per_category, lambda { |category_id|
    includes(:author).where('category_id = ? and status = ?', category_id, 'published')
  }

  scope :category_all_article, lambda {
    Category.includes(:articles).where(articles: { status: 'published' }).order(priority: :desc)
  }

  scope :featured_article, lambda {
    all_published_articles.joins(:votes).group(:id).count.max_by { |_k, v| v }
  }

  scope :most_popular_articles, lambda {
    where(id: all_published_articles.joins(:votes).group(:id).count.sort_by { |_k, v| v }.last(4).map { |a, _b| a })
  }

  scope :user_pub_articles, lambda { |current_user|
    where('author_id = ? and status = ?', current_user, 'published')
  }

  scope :user_save_articles, ->(current_user) { where('author_id = ? and status = ?', current_user, 'saved') }
  scope :user_bookmarks, ->(current_user) { includes(:author).joins(:bookmarks).where('user_id = ? ', current_user) }

  scope :suggested_article, lambda { |tag, category_id|
    all_published_articles.joins(:taggings).where('tag_id = ? or category_id = ? ', tag, category_id)
  }

  default_scope -> { order(created_at: :desc) }

  def tag_list
    tags.collect(&:name).join(',')
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(',').collect { |s| s.strip.downcase }.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end

  def self.all_suggested_article(category_id, article)
    suggested_art_arr = []
    article.tags.each do |tag|
      suggested_art_arr << Article.suggested_article(tag, category_id)
    end
    suggested_art_arr.flatten.uniq - [article]
  end

  def self.search_article(search)
    split_search = search.downcase.split(' ')
    arr = []
    all_published_articles.unscope(:includes).each do |article|
      split_search.map { |word| arr << article if article.title.downcase.split(' ').include?(word) }
    end
    arr.uniq
  end

  private

  def capitalize_title
    self.title = title.capitalize
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :logged_in_user_for_bookmark, only: [:bookmarks]
  before_action :logged_in_user, except: %i[show bookmarks search]
  before_action :non_editing_published_articles, only: %i[edit update]
  before_action :redirect_index_page, only: [:index]

  def index; end

  def new
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
    @articles = Article.all_published_articles
    @comment = Comment.new
    @categories = Category.all
    @most_popular_articles = Article.most_popular_articles
    @all_suggested_articles = Article.all_suggested_article(@article.category.id, @article)
    @pageview = Article.where(author_id: current_user,
                              id: params[:id]).first_or_create
    @pageview.increment!(:views)
  end

  # rubocop:disable Metrics/PerceivedComplexity
  def create
    @article = current_user.articles.build(article_params)
    if params[:save_button]
      @article.status = 'saved'
      if @article.save
        flash['alert-success'] = 'Article saved successfully!'
        render :edit
      else
        render :new
      end
    elsif params[:publish_button]
      @article.status = 'published'
      if @article.save
        flash['alert-success'] = 'Article published successfully!'
        redirect_to article_path(@article)
      else
        render :new
      end
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if params[:save_button]
      @article.status = 'saved'
      if @article.update(article_params)
        redirect_to(request.referer)
        flash['alert-success'] = 'Article saved successfully!'
      else
        render :edit
      end
    elsif params[:publish_button]
      @article.status = 'published'
      if @article.update(article_params)
        flash['alert-success'] = 'Article published successfully!'
        redirect_to article_path(@article)
      else
        render :edit
      end
    end
  end
  # rubocop:enable Metrics/PerceivedComplexity

  def destroy
    @delete_article = Article.find(params[:id])
    @delete_article.destroy
    flash['alert-warning'] = 'Your article has been succesfully deleted!'
    redirect_to saved_articles_path
  end

  def published_articles
    @published_articles = Article.user_pub_articles(current_user)
  end

  def saved_articles
    @saved_articles = Article.user_save_articles(current_user)
  end

  def bookmarks
    @bookmarked_articles = Article.user_bookmarks(current_user)
  end

  def search
    @search_param = params[:q]
    @search_articles = Article.search_article(params[:q])
  end

  private

  def article_params
    params.required(:article).permit(:title, :text, :featured_image, :tag_list,
                                     :category_id, :author_id, :status)
  end

  def logged_in_user_for_bookmark
    return if logged_in?

    flash['alert-danger'] = 'You must be logged in to bookmark an article!'
    redirect_to(request.referer)
  end

  def redirect_index_page
    redirect_to(request.referer)
  end

  def non_editing_published_articles
    @article = Article.find(params[:id])
    return if @article.status != 'published'

    flash['alert-danger'] = 'You cannnot edit a published article!'
    redirect_to article_path(@article)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def string_length(string, length)
    string_sanitize = ActionView::Base.full_sanitizer.sanitize(string)
    string_sanitize.length > length ? "#{string_sanitize[0..length]}..." : string_sanitize
  end

  def get_order_1(num)
    num.odd? ? 2 : 1
  end

  def get_order_2(num)
    num.odd? ? 1 : 2
  end

  def parent_order(num)
    if ((num - 1) % 4).zero?
      1 + (num - 1)
    elsif ((num - 2) % 4).zero?
      3 + (num - 2)
    elsif ((num - 3) % 4).zero?
      2 + (num - 3)
    elsif ((num - 4) % 4).zero?
      4 + (num - 4)
    end
  end

  def comment_count(comment)
    if comment.count.positive?
      pluralize(comment.count, 'Comment')
    else
      'No Comment'
    end
  end

  def min_read(article)
    article_sanitize = ActionView::Base.full_sanitizer.sanitize(article)
    (article_sanitize.length / 100).to_i
  end

  def search_info(search, searched_count)
    searched_info = ''
    if searched_count.present?
      searched_info = "Search for \"#{search}\"<br> "
      searched_info += "Result for #{pluralize(searched_count.count, 'article')}"
    else
      searched_info = if search.present?
                        "No search for \"#{search}\""
                      else
                        'Search for something'
                      end
    end
    searched_info.html_safe
  end

  def article_present(article)
    article.any?
  end

  def category_article_limit(article, limit)
    article[0..limit]
  end

  def article_random(article, num)
    article.sample(num)
  end

  def count_all(model)
    model.count
  end

  def get_strftime(model, time_mode)
    model.strftime(time_mode)
  end

  def sort_array(arr)
    arr.max
  end

  def bookmark_form
    if current_user
      render partial: 'bookmark_form', locals: { article: @article }
    else
      link_to bookmarks_path do
        button_tag fa_icon('bookmark'), class: 'vote-button'
      end
    end
  end
end

app/views/articles/_bookmark_form.html.erb
<% if current_user.bookmarked?(@article) %>

  <%= render partial: 'articles/unbookmark', locals: {article: @article} %>

<% else %>

  <%= render partial: 'articles/bookmark', locals: {article: @article} %>

<% end %>

app/views/articles/_bookmark_from.html.erb
<% if current_user.bookmarked?(@article) %>
  <%= render partial: 'articles/unbookmark', locals: {article: @article} %>
<% else %>
  <%= render partial: 'articles/bookmark', locals: {article: @article} %>
<% end %>

app/views/articles/_comment.html.erb
<ul class="list-group list-group-flush">
  <% @article.comments.each do |comment| %>
    <li class="list-group-item">
      <div class="comment-creator">
        <div class="comment-creator-info d-flex justify-content-between align-items-center">
          <div class="comment-creator-desc d-flex flex-column">
            <div class="comment-name"><%= comment.name %> says...</div>
              <div class="comment-body">
                <p><%= sanitize comment.body %></p>
                <span><%= get_strftime(comment.created_at, "%B %d %Y") %></span>
              </div>
          </div>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/articles/_downvote.html.erb
<%= form_for(current_user.votes.find_by(article_id: @article.id), remote: true, html: { method: :delete }) do |f| %>
  <span class="vote">
    <%= f.button fa_icon('arrow-alt-circle-up', class: "checked"), class: "vote-button" %> &nbsp;
    <span class="view-no"><%= @article.voters.count %></span>
  </span>
<% end %>

app/views/articles/_suggested_articles.html.erb
<div class="col-12 col-md-3 mb-5 mb-md-0">
  <div class="suggested-articles mt-3 text-center">
    <h2 class="section-header pt-0">Suggested Articles</h2>
    <div class="suggested-article-content">
      <% article_random(@articles, 3).each do |suggested_articles| %>
        <%= link_to article_path(suggested_articles.id), class: "suggested-article-link" do %>
          <div class="card mb-4">
            <div class="image ripple suggested-image">
              <%= image_tag(suggested_articles.featured_image_url, alt: suggested_articles.title, class: "card-img-top")%>
            </div>
            <div class="card-body">
              <h5 class="card-title font-weight-"><%= suggested_articles.category.name.capitalize %></h5>
              <p class="card-text"><%= suggested_articles.title %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="popular-articles">
    <div class="list-group">
      <div class="list-group-item list-group-item-action header">
        <h2 class="card-title">Most Popular</h2>
      </div>
      <% @most_popular_articles.each do |popular_articles| %>
        <%= link_to article_path(popular_articles), class: "list-group-item list-group-item-action list" do %>
          <div class="popular-article-item d-flex flex-column">
            <p class="card-text"><%= popular_articles.title %></p>
            <div class="views d-flex align-items-center align-self-end">
             <span class="view">
                <%= fa_icon("arrow-alt-circle-up", class: "checked") %> &nbsp;
                <span class="view-no"><%= count_all(popular_articles.voters) %></span>
              </span>
              <span class="view">
                  <%= fa_icon('eye') %> &nbsp; <span class="view-no"><%= popular_articles.views %></span>
              </span>
              <span class="comment">
                <%= fa_icon('comment-alt') %> &nbsp; <span class="view-no"><%= count_all(popular_articles.comments) %></span>
              </span>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/_unbookmark.html.erb
<%= form_for(current_user.bookmarks.find_by(article_id: @article.id), remote: true, html: { method: :delete }) do |f| %>
  <span class="bookmark">
    <%= f.button fa_icon('bookmark', class: "checked"), class: "vote-button" %> &nbsp;
  </span>
<% end %>

app/views/articles/_vote_form.html.erb
<% if current_user.voted?(@article) %>

  <%= render partial: 'articles/downvote', locals: {article: @article} %>

<% else %>

  <%= render partial: 'articles/vote', locals: {article: @article} %>

<% end %>

app/views/articles/bookmarks.html.erb
<div class="main-content category-articles">
  <div class="category-articles-all">
    <% if article_present(@bookmarked_articles) %>
      <div class="section-heading text-center py-4">
        <h2 class="display-4 py-4">Your Bookmarked Articles</h2>
      </div>

      <div class="category-all-articles d-flex flex-wrap mb-5">
        <% @bookmarked_articles.each_with_index do |article, index| %>
          <div class="article-contents d-flex flex-row flex-wrap order-md-<%= parent_order(index+1) %> order-xl-<%= parent_order(index+1)%>">
            <div class="article-cont p-0 col-12 col-sm-6 order-<%= get_order_1(index) %> order-xl-<%= get_order_1(index) %>">
              <%= image_tag(article.featured_image_url, alt: article.title, class: "img-fluid") %>
            </div>
            <div class="article-cont p-0 col-12 col-sm-6 order-<%= get_order_2(index) %> order-xl-<%= get_order_2(index) %>">
              <div class="article-item-desc">
                <h6><%= link_to article.title.titleize, article_path(article) %></h6>
                <p><%= string_length(article.text, 80) %></p>
                <span>By  <%= article.author.name %></span>
                <div class="attr d-flex justify-content-start align-items-center">
                  <span class="view">
                    <% if count_all(article.votes).positive? %>
                      <%= fa_icon('arrow-alt-circle-up') %> &nbsp;
                      <span class="view-no"><%= count_all(article.votes) %></span>
                    <% else %>
                      <%= fa_icon("arrow-alt-circle-up", class: "vote-button text-dark" )%> &nbsp;
                      <span class="view-no"><%= count_all(article.votes) %></span>
                    <% end %>
                  </span>
                  <span class="comment">
                    <% if count_all(article.comments).positive? %>
                      <%= fa_icon('comment-alt') %> &nbsp;
                      <span class="view-no"><%= count_all(article.comments) %></span>
                    <% else %>
                      <%= fa_icon('comment-alt', class: "text-dark") %> &nbsp;
                      <span class="view-no"><%= count_all(article.comments) %></span>
                    <% end %>
                  </span>
                  <span class="min-read">
                    <%= min_read(article.text) %> mins read
                  </span>
                </div>

              </div>
            </div>
        </div>
        <% end %>
      </div>
    <% else %>
      <h2 class="display-5 text-center no-article-text">You have no bookmarked article!</h2>
    <% end %>

  </div>
</div>

app/views/articles/edit.html.erb
<div class="main-content new-article">
  <div class="article-form">

    <%= form_for(@article, html: { multipart: true }) do |f| %>

      <%= render 'shared/errors', object: f.object %>

      <div class="row">
        <div class="col-12 col-lg-8">
          <div class="group">
            <%= f.text_area :title, autocomplete: 'off', maxlength: "60", class: "input", placeholder: "Title" %>
          </div>
          <div class="group">
            <%= f.label :text, "Text", class: "article-body-label" %>
            <%= f.text_area :text,class: "input article-text-area", id: "article-text-area" %>
          </div>

        </div>
        <div class="col-12 col-lg-4 mt-5">
          <div class="article-featured-image-edit" id="article-featured">
            <div id="display-img" class="display-img">
               <% unless @article.featured_image.blank? %>
                  <%= image_tag(@article.featured_image_url, id: "previewImage") %>
                <% end %>
            </div>
            <%= f.file_field :featured_image, id: "article-image", class: "article-image file-input" %>
             <% if @article.featured_image.blank? %>
              <div id="drop_zone">
                Add Featured Image
              </div>
            <% end %>
          </div>

           <div class="group">
            <div class="input-group mb-2">
              <div class="input-group-prepend">
                <div class="input-group-text"><%= fa_icon('list-alt') %></div>
              </div>
              <%= collection_select(:article, :category_id, Category.all, :id, :name_with_caps, {prompt: "Select Category"}, {class: "form-control cat-select"}) %>
            </div>
          </div>

          <div class="group">
            <div class="input-group mb-2">
              <div class="input-group-prepend">
                <div class="input-group-text"><%= fa_icon('tag') %></div>
              </div>
              <%= f.text_field :tag_list, placeholder: "Article Tags", class: "form-control tag-select" %>

            </div>
            <small class="tag-info">Seperate tags with a comma</small>
          </div>

        </div>
      </div>

      <div class="group">
        <%= f.submit "Save", :name => 'save_button', class: "button" %>
        <%= f.submit "Publish", :name => 'publish_button', class: "button", data: {confirm: 'Are you sure?'} %>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="main-content new-article">
  <div class="article-form">

    <%= form_for(@article, html: { multipart: true }) do |f| %>

      <%= render 'shared/errors', object: f.object %>

      <div class="row">
        <div class="col-12 col-lg-8">
          <div class="group">
            <%= f.text_area :title, autocomplete: 'off', maxlength: "60", class: "input", placeholder: "Title" %>
          </div>
          <div class="group">
            <%= f.label :text, "Text", class: "article-body-label" %>
            <%= f.text_area :text, class: "input article-text-area", id: "article-text-area", placeholder: "Tell your story" %>
          </div>

        </div>
        <div class="col-12 col-lg-4 mt-5 right-column">
          <div class="article-featured-image" id="article-featured">
            <div id="display-img" class="display-img"></div>
            <%= f.file_field :featured_image, id: "article-image", class: "article-image file-input" %>
            <div id="drop_zone" class="drop-zone">
              <h2 class="text-center">Add Featured Image</h2>
            </div>
          </div>
          <div class="input-group-side">
            <div class="group">
              <div class="input-group mb-2">
                <div class="input-group-prepend">
                  <div class="input-group-text"><%= fa_icon('list-alt') %></div>
                </div>
                <%= collection_select(:article, :category_id, Category.all, :id, :name_with_caps, {prompt: "Select Category"}, {class: "form-control cat-select"}) %>
              </div>
            </div>

            <div class="group">
              <div class="input-group mb-2">
                <div class="input-group-prepend">
                  <div class="input-group-text"><%= fa_icon('tag') %></div>
                </div>
                <%= f.text_field :tag_list, placeholder: "Article Tags", class: "form-control tag-select" %>

              </div>
              <small class="tag-info">Seperate tags with a comma</small>
            </div>
          </div>
        </div>
      </div>

      <div class="group">
        <%= f.submit "Save", :name => 'save_button', class: "button" %>
        <%= f.submit "Publish", :name => 'publish_button', class: "button", data: {confirm: 'Are you sure?'} %>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/published_articles.html.erb
<div class="main-content category-articles">
  <div class="category-articles-all">
    <% if article_present(@published_articles) %>
      <div class="section-heading text-center py-4">
        <h2 class="display-4 py-4">Your Published Articles</h2>
      </div>


      <div class="category-all-articles d-flex flex-wrap mb-5">
        <% @published_articles.each_with_index do |article, index| %>
         <div class="article-contents d-flex flex-row flex-wrap order-md-<%= parent_order(index+1) %> order-xl-<%= parent_order(index+1)%>">
          <div class="article-cont p-0 col-12 col-sm-6 order-<%= get_order_1(index) %> order-xl-<%= get_order_1(index) %>">
            <%= image_tag(article.featured_image_url, alt: article.title, class: "img-fluid") %>
          </div>
          <div class="article-cont p-0 col-12 col-sm-6 order-<%= get_order_2(index) %> order-xl-<%= get_order_2(index) %>">
            <div class="article-item-desc">
              <h6><%= link_to article.title.titleize, article_path(article) %></h6>
              <p><%= string_length(article.text, 80) %></p>
              <div class="attr d-flex justify-content-start align-items-center">
                <span class="view">
                  <% if count_all(article.votes).positive? %>
                    <%= fa_icon('arrow-alt-circle-up') %> &nbsp;
                    <span class="view-no"><%= count_all(article.votes) %></span>
                  <% else %>
                    <%= fa_icon("arrow-alt-circle-up", class: "vote-button text-dark" )%> &nbsp;
                    <span class="view-no"><%= count_all(article.votes) %></span>
                  <% end %>
                </span>
                <span class="comment">
                  <% if count_all(article.comments).positive? %>
                    <%= fa_icon('comment-alt') %> &nbsp;
                    <span class="view-no"><%= count_all(article.comments) %></span>
                  <% else %>
                    <%= fa_icon('comment-alt', class: "text-dark") %> &nbsp;
                    <span class="view-no"><%= count_all(article.comments) %></span>
                  <% end %>
                  </span>
                <span class="min-read">
                  <%= min_read(article.text) %> mins read
                </span>
              </div>

            </div>
          </div>
        </div>
        <% end %>
      </div>
    <% else %>
      <h2 class="display-5 text-center no-article-text">You have no published article!</h2>
    <% end %>
  </div>
</div>

app/views/articles/saved_articles.html.erb
<div class="main-content category-articles">
  <div class="category-articles-all">
    <% if article_present(@saved_articles) %>
      <div class="section-heading text-center py-4">
        <h2 class="display-4 py-4">Your Saved Articles</h2>
      </div>

      <div class="category-all-articles d-flex flex-wrap mb-5">
        <% @saved_articles.each_with_index do |article, index| %>
          <div class="article-contents d-flex flex-row flex-wrap order-md-<%= parent_order(index+1) %> order-xl-<%= parent_order(index+1)%>">
            <div class="article-cont p-0 col-12 col-sm-6 order-<%= get_order_1(index) %> order-xl-<%= get_order_1(index) %>">
              <%= image_tag(article.featured_image_url, alt: article.title, class: "img-fluid") %>
            </div>
            <div class="article-cont position-relative p-0 col-12 col-sm-6 order-<%= get_order_2(index) %> order-xl-<%= get_order_2(index) %>">
              <div class="article-item-desc">
                <h6><%= link_to article.title.titleize, edit_article_path(article) %></h6>
                <p><%= string_length(article.text, 80) %></p>
                <div class="attr d-flex justify-content-start align-items-center">
                  <span class="saved-art min-read">
                    <%= min_read(article.text) %> mins read
                  </span>
                </div>
                <span class="saved-art view">
                  <%= link_to article_path(article), method: :delete, data: {confirm: "Are you sure you want to delete this article?"} do %>
                    <%= fa_icon('times-circle') %>
                  <% end %>
                </span>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <h2 class="display-5 text-center no-article-text">You have no saved article!</h2>
    <% end %>

  </div>
</div>

app/views/articles/show.html.erb
<div class="main-content article-page container">
  <div class="category-articles-all">
    <div class="row">
      <div class="col-12 col-md-9">
        <div class="article-card">
          <h1 class="card-cat"><%= @article.category.name.upcase %></h1>
          <h2 class="card-title"><%= @article.title.titleize %></h2>
          <div class="article-info d-md-flex flex-column flex-sm-column flex-md-row">
            <div class="info1">
              <div class="author-name">
                By <%= @article.author.name.titleize %>
              </div>
              <div class="date">

                <%= get_strftime(@article.created_at, "%b %-d %Y") %>
              </div>
            </div>
            <div class="info2 d-flex justify-content-start mt-3">
              <div class="view">
                <%= fa_icon('eye eye-views') %> &nbsp; <span class="view-no"><%= @article.views %></span>
              </div>
              <div class="vote-form" id="vote_form">
              <% if current_user %>
                <%= render partial: 'vote_form', locals: {article: @article} %>
              <% else %>
                <%= link_to votes_path, class: "pseudo-vote" do %>
                  <span class="vote">
                    <%= button_tag fa_icon("arrow-alt-circle-up", type: :regular), class: "vote-button" %> &nbsp;
                    <span class="view-no"><%= count_all(@article.votes) %></span>
                  </span>
                <% end %>
              <% end %>
              </div>
              <div class="bookmark-form" id="bookmark_form">
                <%= bookmark_form %>
              </div>
            </div>
          </div>
          <%= image_tag(@article.featured_image_url, alt: @article.title, class: "img-fluid") %>
          <div class="card-body">
            <div class="card-text"><%= @article.text.html_safe %></div>
          </div>
          <div class="author-social-link">
            <hr>
            <div class="author-info d-flex flex-wrap justify-content-center justify-content-sm-between align-items-center">
              <% if @article.tags.any? %>
                <div class="article-tags">
                  Tags:
                  <% @article.tags.each_with_index do |tag, index| %>
                     <% if index == (@article.tags.length-1) %>
                      <%= "#{tag.name}." %>
                    <% else %>
                      <%= "#{tag.name}," %>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
              <div class="author-social-icons">
                <%= link_to fa_icon('linkedin', type: :brand, size: '3x' ),
                 @article.author.linkedin, class: "linkedin", target: :_blank %>
                <%= link_to fa_icon('twitter-square', type: :brand, size: '3x' ), @article.author.twitter, class: "twitter", target: :_blank %>
              </div>
            </div>
          <hr>
          </div>
        </div>

        <div class="comment-card card">
          <div class="comment-header card-header">
            <div class="comment-title" id="comment-title">
              <%= comment_count(@article.comments) %>
            </div>
            <div class="write-comment">
              <a href="#new-comment" class="write-comment-btn button">Post a Comment</a>
            </div>
          </div>
          <div class="card-body">
            <div class="all-comments" id="all-comments">

              <%= render partial: 'comment', locals: {article: @article} %>

            </div>
            <div class="comment-section new-comment" id="new-comment">
              <div class="comment-form">

               <%= render 'comments/comment_form' %>

              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-12 col-md-3">
        <div class="suggested-articles mt-3 text-center">

          <% if article_present(@all_suggested_articles) %>
            <h2 class="section-header">Suggested Articles</h2>
          <% end %>
          <div class="suggested-article-content">
            <% article_random(@all_suggested_articles, 4).each do |suggested_articles| %>
              <%= link_to article_path(suggested_articles.id), class: "suggested-article-link" do %>
                <div class="card mb-4">
                  <div class="image ripple suggested-image">
                    <%= image_tag(suggested_articles.featured_image_url, alt: suggested_articles.title, class: "card-img-top")%>
                  </div>
                  <div class="card-body">
                    <h5 class="card-title"><%= suggested_articles.category.name.capitalize %></h5>
                    <p class="card-text"><%= suggested_articles.title %></p>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>

        <div class="popular-articles">
          <div class="list-group">
            <div class="list-group-item list-group-item-action header">
              <h1 class="card-cat"><%= @article.category.name.capitalize %></h1>
              <h2 class="card-title">Most Popular</h2>
            </div>
            <% @most_popular_articles.each_with_index do |popular_articles, index| %>
              <%= link_to article_path(popular_articles), class: "list-group-item list-group-item-action list" do %>
                <div class="popular-article-item d-flex flex-column">
                  <p class="card-text"><%= popular_articles.title %></p>
                  <div class="views d-flex align-items-center align-self-end">
                    <span class="view">
                       <%= fa_icon('eye') %> &nbsp; <span class="view-no"><%= popular_articles.views %></span>
                    </span>
                    <span class="comment">
                     <%= fa_icon('comment-alt') %> &nbsp; <span class="view-no"><%= count_all(popular_articles.comments) %></span>
                    </span>
                  </div>
                </div>
             <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>