config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :users, except: [:show, :edit]
  resources :categories, only: [:index, :create, :destroy]
  resources :comments, only: [:new, :create]
  resources :votes, only: [:index, :create, :destroy]
  resources :bookmarks, only: [:create, :destroy]
  resources :tags
  resources :articles

  get 'sessions/new'
  get '/signup',  to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'published_articles', to: 'articles#published_articles'
  get 'saved_articles', to: 'articles#saved_articles'
  get 'bookmarks', to: 'articles#bookmarks'
  get 'search', to: 'articles#search'
  get 'create_category', to: 'categories#new'

  get 'profile', to: 'users#show'
  get '/edit_profile', to: 'users#edit'
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  has_many :articles, foreign_key: 'author_id', dependent: :destroy

  has_many :votes, foreign_key: 'user_id', dependent: :destroy
  has_many :voted_articles, through: :votes, source: :article

  has_many :bookmarks, foreign_key: 'user_id', dependent: :destroy
  has_many :bookmarked_articles, through: :bookmarks, source: :article

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :name, presence: true, length: { in: 3..50 }
  validates :username, presence: true, length: { in: 3..50 },
                       uniqueness: { case_sensitive: false }
  validates :email, presence: true, length: { maximum: 255 },
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: { maximum: 255 }

  mount_uploader :avatar, AvatarUploader
  before_save :downcase_email
  has_secure_password

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticate?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget_digest_db
    update_attribute(:remember_digest, nil)
  end

  def vote(article)
    voted_articles << article
  end

  def unvote(article)
    voted_articles.delete(article)
  end

  def voted?(article)
    voted_articles.include?(article)
  end

  def bookmark(article)
    bookmarked_articles << article
  end

  def unbookmark(article)
    bookmarked_articles.delete(article)
  end

  def bookmarked?(article)
    bookmarked_articles.include?(article)
  end

  private

  def downcase_email
    self.email = email.downcase
    self.username = username.downcase
  end

  def save_avatar
    avatar = gravatar_for(email)
    update_column(:avatar, avatar)
  end

  def gravatar_for(email, size: 80)
    gravatar_id = Digest::MD5.hexdigest(email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    gravatar_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, except: %i[new create]
  before_action :already_logged_in, only: %i[new create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      create_session(@user)
      create_cookies(@user)
      flash['alert-success'] = 'Welcome to the great Lifestyle platform'
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = current_user
    @articles = @user.articles
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash['alert-success'] = 'User updated succesfully'
      redirect_to profile_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.required(:user).permit(:name, :username, :email,
                                  :twitter, :linkedin, :avatar,
                                  :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, class_name)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=200"
    image_tag(gravatar_url, alt: user.name, class: class_name)
  end

  def avatar(user, class_name)
    if user.avatar_url.present?
      image_tag(user.avatar_url, alt: user.name, class: class_name)
    else
      gravatar_for(user, class_name)
    end
  end

  def avatar_present(avatar)
    avatar.present?
  end

  def session_status
    if controller_name == 'sessions'
      'Login'
    else
      'Register'
    end
  end

  def gravatar_image
    if avatar_present(current_user.avatar)
      image_tag(current_user.avatar_url, class: 'avatar', id: 'previewImage')
    else
      gravatar_for(current_user, 'profile-img-lg')
    end
  end
end

app/views/users/edit.html.erb
<div class="signup-login-forms">
  <div class="form-contents">
    <div class="login-html edit-form">
      <div class="title text-center">
        <%= content_tag :h2, "Edit Profile", class: "sign-up tab active text-center"%>
      </div>
      <div class="login-form">
        <div class="sign-up-form">

          <%= form_for(@user) do |f| %>

            <%= render 'shared/errors', object: f.object %>

            <div class="row">
              <div class="col-12 col-sm-6 order-2 order-sm-1">
                <div class="group">
                  <%= f.label :name, class: 'label'%>
                  <%= f.text_field :name, class: "input"%>
                </div>
                <div class="group">
                  <%= f.label :username, class: 'label'%>
                  <%= f.text_field :username, class: "input"%>
                </div>
                <div class="group">
                  <%= f.label :email, class: 'label'%>
                  <%= f.email_field :email, class: "input"%>
                </div>
                <div class="group">
                  <%= f.label :twitter, 'Twitter Profile Link', class: 'label'%>
                  <%= f.text_field :twitter, class: "input" %>
                </div>
                <div class="group">
                  <%= f.label :linkedin, 'Linkedin Profile Link', class: 'label'%>
                  <%= f.text_field :linkedin, class: "input" %>
                </div>
                <div class="group">
                  <%= f.label :password, class: 'label'%>
                  <%= f.password_field :password, class: "input"%>
                </div>
                <div class="group text-center">
                  <%= f.submit "Update", class: "button d-inline edit-profile" %>
                </div>
              </div>
              <div class="col-12 col-sm-6 order-1 order-sm-2 mb-5 mb-sm-0">
                <div class="profile-avatar" id="article-featured">
                  <div class="avatar">
                    <div id="display-avatar" class="display-avatar">
                      <%= gravatar_image %>
                    </div>

                    <%= f.label :avatar, "Change Profile Image", class: "image-label" %>
                    <%= f.file_field :avatar, id: "user_avatar", class: "user-avatar file-input" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
         <% end %>
        </div>
      </div>
    </div>
</div>

app/views/users/new.html.erb
<div class="signup-login-forms">
  <div class="form-contents">
    <div class="login-html">
      <%= link_to "Log In", login_path, class: "sign-in tab"%>
      <%= link_to "Register", signup_path, class: "sign-up tab active"%>
      <div class="login-form">
        <div class="sign-up-form">
          <%= form_for(@user) do |f| %>

            <%= render 'shared/errors', object: f.object %>

            <div class="group">
              <%= f.label :name, class: 'label'%>
              <%= f.text_field :name, class: "input"%>
            </div>
            <div class="group">
              <%= f.label :username, class: 'label'%>
              <%= f.text_field :username, class: "input"%>
            </div>
            <div class="group">
              <%= f.label :email, class: 'label'%>
              <%= f.email_field :email, class: "input"%>
            </div>
            <div class="group">
              <%= f.label :password, class: 'label'%>
              <%= f.password_field :password, class: "input"%>
            </div>
            <div class="group">
              <%= f.submit "Register", class: "button", id: "register" %>
            </div>
            <div class="hr"></div>
            <div class="foot-lnk">
              <%= link_to 'Already Member?', login_path() %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
   <%= render 'shared/sm-login'%>
  </div>
</div>

app/views/users/show.html.erb
<div class="signup-login-forms">
  <div class="form-contents">
    <div class="login-html edit-form">
      <div class="title text-center">
        <%= content_tag :h2, "Profile", class: "sign-up tab active text-center"%>
      </div>
      <div class="login-form">
        <div class="sign-up-form">
          <%= form_for(current_user) do |f| %>
            <div class="row">
              <div class="col-12 col-sm-6 order-2 order-sm-1">
                <div class="group">
                  <%= f.label :name, class: 'label'%>
                  <%= f.text_field :name, class: "input", disabled: true %>
                </div>
                <div class="group">
                  <%= f.label :username, class: 'label'%>
                  <%= f.text_field :username, class: "input", disabled: true %>
                </div>
                <div class="group">
                  <%= f.label :email, class: 'label'%>
                  <%= f.email_field :email, class: "input", disabled: true %>
                </div>
                <div class="group">
                  <%= f.label :twitter, 'Twitter Profile Link', class: 'label'%>
                  <%= f.text_field :twitter, class: "input", disabled: true %>
                </div>
                <div class="group">
                  <%= f.label :linkedin, 'Linkedin Profile Link', class: 'label'%>
                  <%= f.text_field :linkedin, class: "input", disabled: true %>
                </div>
                <div class="group text-center">
                  <%= link_to "Edit Profile", edit_profile_path, class: "button edit-button d-inline", id: "edit-profile" %>
                </div>
              </div>
              <div class="col-12 col-sm-6 order-1 order-sm-2 mb-5 mb-sm-0">
                <div class="profile-avatar">
                  <%= gravatar_image  %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    </div>
  </div>